const translations={
  en:{navMarket:'Market',navStudio:'Studio',navMethod:'Method',navContact:'Start a conversation ↗',marketPulse:'Market pulse',disclaimer:'Illustrative delayed data · For demonstration only',heroEyebrow:'Quantitative research studio · Hong Kong / Worldwide',heroTitle:'Measure the<br><em>unseen.</em>',heroBody:'We build intelligent systems for people who believe the future belongs to those who can read its patterns.',heroCta:'Enter the signal',scroll:'Scroll to discover',quantView:'The quantified view',signalTitle:'Signal over<br><em>noise.</em>',signalBody:'Our systems read thousands of market relationships in motion, turning complexity into a clear, disciplined point of view.',strategy:'Strategy / A01 Momentum',jan:'Jan',mar:'Mar',jun:'Jun',sep:'Sep',sharpe:'Sharpe ratio 1.84',drawdown:'Max drawdown −6.2%',updated:'Updated just now',confidence:'Model confidence',signals:'Across 2,840 signals',riskReward:'Risk / reward',allocation:'Adaptive allocation',classicalLens:'A classical lens / a computational eye',oldWorlds:'Old worlds,<br><em>new signals.</em>',oldWorldsBody:'We borrow the patience of the old masters and apply it to the speed of modern markets: observe deeply, reduce noise, act with intent.',plateOne:'Plate 01 / Flow state',plateTwo:'Plate 02 / Long horizon',howWeWork:'How we work',methodOneTitle:'Find the signal',methodOneBody:'We identify durable relationships hidden beneath market noise.',methodTwoTitle:'Build the model',methodTwoBody:'Research systems turn uncertainty into measured, explainable decisions.',methodThreeTitle:'Adapt with discipline',methodThreeBody:'Strategies evolve with the market while risk remains firmly governed.',contactEyebrow:'A conversation worth beginning',contactTitle:'Build for the<br><em>long horizon.</em>',contactBody:'For institutional partnerships, research collaboration and strategic enquiries.',footerLine:'Quantitative research · Hong Kong · 2026',footerRisk:'Research material · Not investment advice'},
  'zh-CN':{navMarket:'市场洞察',navStudio:'关于我们',navMethod:'研究方法',navContact:'开启对话 ↗',marketPulse:'市场脉搏',disclaimer:'延迟演示数据 · 仅供界面展示',heroEyebrow:'量化研究机构 · 香港 / 服务全球',heroTitle:'洞察规律，<br><em>度量未知。</em>',heroBody:'我们以严谨研究与智能系统解读市场结构，让复杂信息转化为可验证、可执行的判断。',heroCta:'探索量化视角',scroll:'向下探索',quantView:'量化视角',signalTitle:'穿越噪声，<br><em>看见信号。</em>',signalBody:'系统持续分析数千组动态市场关系，将复杂变化提炼为清晰、审慎且可解释的研究观点。',strategy:'策略 / A01 动量模型',jan:'一月',mar:'三月',jun:'六月',sep:'九月',sharpe:'夏普比率 1.84',drawdown:'最大回撤 −6.2%',updated:'刚刚更新',confidence:'模型置信度',signals:'综合 2,840 个信号',riskReward:'风险收益比',allocation:'自适应资产配置',classicalLens:'古典之眼 / 计算之思',oldWorlds:'承古典之静，<br><em>见时代之变。</em>',oldWorldsBody:'我们借鉴古典大师耐心观察世界的方式，并将这种专注应用于高速变化的现代市场：深入观察、过滤噪声、审慎行动。',plateOne:'图版 01 / 流动秩序',plateTwo:'图版 02 / 长期视野',howWeWork:'我们的研究方法',methodOneTitle:'识别有效信号',methodOneBody:'从市场噪声之下寻找稳定、可重复验证的关系。',methodTwoTitle:'构建研究模型',methodTwoBody:'以系统化研究将不确定性转化为可衡量、可解释的决策。',methodThreeTitle:'在纪律中进化',methodThreeBody:'策略随市场持续演进，同时始终坚持明确的风险边界。',contactEyebrow:'从一次有价值的对话开始',contactTitle:'立足当下，<br><em>着眼长期。</em>',contactBody:'欢迎就机构合作、量化研究与战略议题与我们联系。',footerLine:'量化研究 · 香港 · 2026',footerRisk:'研究资料 · 不构成任何投资建议'},
  'zh-TW':{navMarket:'市場洞察',navStudio:'關於我們',navMethod:'研究方法',navContact:'開啟對話 ↗',marketPulse:'市場脈搏',disclaimer:'延遲示範數據 · 僅供介面展示',heroEyebrow:'量化研究機構 · 香港 / 服務全球',heroTitle:'洞察規律，<br><em>度量未知。</em>',heroBody:'我們以嚴謹研究與智慧系統解讀市場結構，讓複雜資訊轉化為可驗證、可執行的判斷。',heroCta:'探索量化視角',scroll:'向下探索',quantView:'量化視角',signalTitle:'穿越雜訊，<br><em>看見訊號。</em>',signalBody:'系統持續分析數千組動態市場關係，將複雜變化提煉為清晰、審慎且可解釋的研究觀點。',strategy:'策略 / A01 動量模型',jan:'一月',mar:'三月',jun:'六月',sep:'九月',sharpe:'夏普比率 1.84',drawdown:'最大回撤 −6.2%',updated:'剛剛更新',confidence:'模型置信度',signals:'綜合 2,840 個訊號',riskReward:'風險報酬比',allocation:'自適應資產配置',classicalLens:'古典之眼 / 計算之思',oldWorlds:'承古典之靜，<br><em>見時代之變。</em>',oldWorldsBody:'我們借鑑古典大師耐心觀察世界的方式，並將這份專注應用於高速變化的現代市場：深入觀察、過濾雜訊、審慎行動。',plateOne:'圖版 01 / 流動秩序',plateTwo:'圖版 02 / 長期視野',howWeWork:'我們的研究方法',methodOneTitle:'辨識有效訊號',methodOneBody:'從市場雜訊之下尋找穩定、可重複驗證的關係。',methodTwoTitle:'建構研究模型',methodTwoBody:'以系統化研究將不確定性轉化為可衡量、可解釋的決策。',methodThreeTitle:'在紀律中演進',methodThreeBody:'策略隨市場持續演進，同時始終堅守明確的風險邊界。',contactEyebrow:'從一次有價值的對話開始',contactTitle:'立足當下，<br><em>著眼長期。</em>',contactBody:'歡迎就機構合作、量化研究與策略議題與我們聯繫。',footerLine:'量化研究 · 香港 · 2026',footerRisk:'研究資料 · 不構成任何投資建議'}
};

function setLanguage(lang){const dict=translations[lang]||translations.en;document.documentElement.lang=lang;document.body.dataset.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const value=dict[el.dataset.i18n];if(value!==undefined)el.textContent=value});document.querySelectorAll('[data-i18n-html]').forEach(el=>{const value=dict[el.dataset.i18nHtml];if(value!==undefined)el.innerHTML=value});document.querySelectorAll('.lang-switcher button').forEach(btn=>btn.classList.toggle('active',btn.dataset.lang===lang));localStorage.setItem('aura-lang',lang)}

document.querySelector('.lang-switcher').addEventListener('click',event=>{const lang=event.target.dataset.lang;if(lang)setLanguage(lang)});
const tickers={spx:1.24,ndx:.86,btc:2.18};
function tick(){const now=new Date();document.querySelector('#clock').textContent=`LIVE / ${now.toLocaleTimeString('en-GB')}`;Object.entries(tickers).forEach(([id,value])=>{const next=value+(Math.random()-.47)*.18;tickers[id]=next;document.querySelector('#'+id).textContent=`${next>=0?'+':''}${next.toFixed(2)}%`});document.querySelector('#confidence').textContent=(87.2+Math.random()*1.2).toFixed(1)}
translations.en.navMarket='Research';translations.en.navMethod='Strategies';translations.en.navStudio='Studio';translations['zh-CN'].navMarket='量化研究';translations['zh-CN'].navMethod='策略体系';translations['zh-CN'].navStudio='理念与团队';translations['zh-TW'].navMarket='量化研究';translations['zh-TW'].navMethod='策略體系';translations['zh-TW'].navStudio='理念與團隊';
setLanguage(localStorage.getItem('aura-lang')||'en');tick();setInterval(tick,2500);
const atlasNav=document.querySelector('.navlinks');if(atlasNav&&!atlasNav.querySelector('[href="archive.html"]'))atlasNav.insertAdjacentHTML('beforeend','<a href="archive.html">Atlas</a>');
if(!document.querySelector('link[rel="icon"]')){const auraIcon=document.createElement('link');auraIcon.rel='icon';auraIcon.type='image/svg+xml';auraIcon.href='public/brand/aura-mark.svg';document.head.appendChild(auraIcon)}
