(function(){
  const copy={
    en:{heroEyebrow:'Systema / live research folio',heroTitle:'Numbers move.<br><em>Theory gives them form.</em>',heroBody:'A working field for observing price movement, testing assumptions and translating mathematical structure into disciplined market decisions.',status:'Model stream active',delay:'Illustrative delayed data',observeEyebrow:'I / Market observatory',observeTitle:'Price is a path,<br><em>not a point.</em>',observeBody:'We read return, dispersion and liquidity together. The aim is not to predict every movement, but to distinguish structure from accident.',pathTitle:'Normalized equity path',return:'Annualized return',drawdown:'Max drawdown',sharpe:'Sharpe',volTitle:'Volatility cone',volBody:'Realized volatility remains below its long-run median while breadth expands.',plateObserve:'Plate 01 / Observation before action',modelEyebrow:'II / Model workshop',modelTitle:'Assumptions enter.<br><em>Evidence returns.</em>',modelBody:'Every model is a compact argument about the market. We expose its inputs, uncertainty and failure conditions.',bsTitle:'Black–Scholes call value',modelValue:'Model value',varianceTitle:'Portfolio variance',riskBudget:'Risk budget used',bayesTitle:'Posterior conviction',prior:'Prior',posterior:'Posterior',evidence:'Evidence strength',factorEyebrow:'III / Factor field',factorTitle:'Many variables.<br><em>One governed exposure.</em>',factorBody:'Signals are orthogonalized, cost-adjusted and constrained before they enter a portfolio.',momentum:'Momentum',quality:'Quality',value:'Value',volatility:'Volatility',liquidity:'Liquidity',corrTitle:'Cross-asset correlation',plateRisk:'Plate 02 / Risk at the boundary',disclaimer:'All market figures and calculations are illustrative, delayed and provided for interface demonstration only. They do not constitute investment advice.',researchLink:'Read the research discipline ↗',footer:'Quantitative laboratory · Hong Kong · 2026',risk:'Research material · Not investment advice'},
    'zh-CN':{heroEyebrow:'系统 / 实时研究手稿',heroTitle:'数字持续流动，<br><em>理论赋予其形态。</em>',heroBody:'在这里观察价格运动、检验假设，并将数学结构转化为有纪律的市场判断。',status:'模型数据流运行中',delay:'延迟示意数据',observeEyebrow:'I / 市场观测台',observeTitle:'价格是一条路径，<br><em>而非孤立的点。</em>',observeBody:'我们同时观察收益、离散度与流动性。目标不是预测每一次波动，而是区分结构与偶然。',pathTitle:'标准化权益曲线',return:'年化收益',drawdown:'最大回撤',sharpe:'夏普比率',volTitle:'波动率锥',volBody:'实际波动率低于长期中位数，同时市场广度持续扩张。',plateObserve:'图版 01 / 行动之前，先观察',modelEyebrow:'II / 模型工坊',modelTitle:'假设进入系统，<br><em>证据返回判断。</em>',modelBody:'每个模型都是关于市场的精炼论证。我们公开它的输入、不确定性与失效条件。',bsTitle:'Black–Scholes 看涨期权估值',modelValue:'模型估值',varianceTitle:'投资组合方差',riskBudget:'已使用风险预算',bayesTitle:'后验置信度',prior:'先验',posterior:'后验',evidence:'证据强度',factorEyebrow:'III / 因子场',factorTitle:'众多变量，<br><em>归于受控敞口。</em>',factorBody:'所有信号在进入组合前都会经过正交化、成本调整与约束处理。',momentum:'动量',quality:'质量',value:'价值',volatility:'波动率',liquidity:'流动性',corrTitle:'跨资产相关矩阵',plateRisk:'图版 02 / 风险存在于边界',disclaimer:'全部市场数据与理论计算均为延迟示意，仅用于界面展示，不构成投资建议。',researchLink:'阅读研究纪律 ↗',footer:'量化实验室 · 香港 · 2026',risk:'研究资料 · 不构成投资建议'},
    'zh-TW':{heroEyebrow:'系統 / 即時研究手稿',heroTitle:'數字持續流動，<br><em>理論賦予其形態。</em>',heroBody:'在此觀察價格運動、檢驗假設，並將數學結構轉化為有紀律的市場判斷。',status:'模型資料流運行中',delay:'延遲示意資料',observeEyebrow:'I / 市場觀測台',observeTitle:'價格是一條路徑，<br><em>而非孤立的點。</em>',observeBody:'我們同時觀察收益、離散度與流動性。目標不是預測每一次波動，而是區分結構與偶然。',pathTitle:'標準化權益曲線',return:'年化收益',drawdown:'最大回撤',sharpe:'夏普比率',volTitle:'波動率錐',volBody:'實際波動率低於長期中位數，同時市場廣度持續擴張。',plateObserve:'圖版 01 / 行動之前，先觀察',modelEyebrow:'II / 模型工坊',modelTitle:'假設進入系統，<br><em>證據返回判斷。</em>',modelBody:'每個模型都是關於市場的精煉論證。我們公開其輸入、不確定性與失效條件。',bsTitle:'Black–Scholes 看漲期權估值',modelValue:'模型估值',varianceTitle:'投資組合方差',riskBudget:'已使用風險預算',bayesTitle:'後驗置信度',prior:'先驗',posterior:'後驗',evidence:'證據強度',factorEyebrow:'III / 因子場',factorTitle:'眾多變數，<br><em>歸於受控曝險。</em>',factorBody:'所有訊號在進入組合前都會經過正交化、成本調整與約束處理。',momentum:'動量',quality:'品質',value:'價值',volatility:'波動率',liquidity:'流動性',corrTitle:'跨資產相關矩陣',plateRisk:'圖版 02 / 風險存在於邊界',disclaimer:'全部市場數據與理論計算均為延遲示意，僅用於介面展示，不構成投資建議。',researchLink:'閱讀研究紀律 ↗',footer:'量化實驗室 · 香港 · 2026',risk:'研究資料 · 不構成投資建議'}
  };
  Object.assign(copy.en,{pathTitle:'Public market pulse',liveFeed:'LIVE / DELAYED BY EXCHANGE',marketSource:'Market feed by TradingView',spaceXNote:'SpaceX Class A shares began trading on Nasdaq in June 2026. This panel follows SPCX beside listed aerospace peers for sector context.',delay:'Connected market feed · exchange delays may apply'});
  Object.assign(copy['zh-CN'],{pathTitle:'公开市场脉搏',liveFeed:'联网行情 / 延迟依交易所规则',marketSource:'行情数据由 TradingView 提供',spaceXNote:'SpaceX A 类股票已于 2026 年 6 月登陆纳斯达克。本图版跟踪 SPCX，并以其他上市航天企业提供行业参照。',delay:'联网行情 · 可能存在交易所延迟'});
  Object.assign(copy['zh-TW'],{pathTitle:'公開市場脈搏',liveFeed:'聯網行情 / 延遲依交易所規則',marketSource:'行情資料由 TradingView 提供',spaceXNote:'SpaceX A 類股票已於 2026 年 6 月登陸納斯達克。本圖版追蹤 SPCX，並以其他上市航太企業提供產業參照。',delay:'聯網行情 · 可能存在交易所延遲'});
  function apply(lang){const d=copy[lang]||copy.en;document.documentElement.lang=lang;document.body.dataset.lang=lang;document.querySelectorAll('[data-quant]').forEach(el=>{if(d[el.dataset.quant])el.textContent=d[el.dataset.quant]});document.querySelectorAll('[data-quant-html]').forEach(el=>{if(d[el.dataset.quantHtml])el.innerHTML=d[el.dataset.quantHtml]})}
  document.addEventListener('click',e=>{if(e.target.matches('.lang-switcher button'))setTimeout(()=>apply(e.target.dataset.lang),0)});apply(localStorage.getItem('aura-lang')||'en');
  const base={AAPL:[226.41,.82],MSFT:[424.73,.46],NVDA:[188.92,1.31],TSLA:[314.08,-.37],HSI:[25081,.55],VIX:[17.24,-1.08]};let n=0;
  function tick(){const now=new Date();document.querySelector('#lab-time').textContent='UTC+8 / '+now.toLocaleTimeString('en-GB',{hour12:false,timeZone:'Asia/Hong_Kong'});document.querySelectorAll('[data-symbol]').forEach((el,i)=>{const [p,c]=base[el.dataset.symbol];const drift=Math.sin(n*.42+i)*p*.00045;const change=c+Math.sin(n*.31+i*1.4)*.07;el.querySelector('strong').textContent=(p+drift).toLocaleString('en-US',{minimumFractionDigits:p>1000?0:2,maximumFractionDigits:p>1000?0:2});const out=el.querySelector('i');out.textContent=(change>=0?'+':'')+change.toFixed(2)+'%';out.classList.toggle('down',change<0)});n++}
  tick();setInterval(tick,2600);
})();
